version: 2
updates:
  # TODO: gha
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "daily"
#      time: "09:00"
#      timezone: "America/Mexico_City"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Mexico_City"